version: 2

updates:
  - package-ecosystem: gomod
    directory: /go
    target-branch: dev
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
      timezone: Asia/Shanghai

  - package-ecosystem: npm
    directory: /webui
    target-branch: dev
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
      timezone: Asia/Shanghai

  - package-ecosystem: github-actions
    directory: /.github/workflows
    target-branch: dev
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
      timezone: Asia/Shanghai